import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { useLocation } from "wouter";
import DashboardShell from "@/components/DashboardShell";
import RichTextEditor from "@/components/RichTextEditor";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Label } from "@/components/ui/label";
import {
  AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent,
  AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  Plus, Edit, Trash2, Eye, Globe, FileText, Clock, Calendar, Rss,
  ExternalLink, BookOpen, Sparkles, ArrowLeft, X, Search,
  Image as ImageIcon, Upload, Loader2,
} from "lucide-react";
import { toast } from "sonner";

type BlogPost = {
  id: number; title: string; slug: string; excerpt: string | null; content: string;
  category: string | null; tags: string | null; author: string | null;
  status: "draft" | "published"; readingTimeMinutes: number | null;
  publishedAt: Date | null; isAutoGenerated: boolean | null;
  createdAt: Date; updatedAt: Date;
};

type PostForm = {
  title: string; slug: string; excerpt: string; content: string;
  category: string; tags: string; author: string;
  readingTimeMinutes: number; status: "draft" | "published";
  coverImageUrl: string;
};

const emptyForm: PostForm = {
  title: "", slug: "", excerpt: "", content: "", category: "",
  tags: "", author: "Lynx AI Team", readingTimeMinutes: 5, status: "draft",
  coverImageUrl: "",
};

function slugify(text: string) {
  return text.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9\s-]/g, "").replace(/\s+/g, "-").replace(/-+/g, "-").trim();
}

function formatDate(date: Date | string | null) {
  if (!date) return "—";
  return new Date(date).toLocaleDateString("es-ES", { year: "numeric", month: "short", day: "numeric" });
}

export default function DashboardBlog() {
  const { user } = useAuth();
  const [, navigate] = useLocation();
  const utils = trpc.useUtils();

  const [view, setView] = useState<"list" | "editor">("list");
  const [editingPost, setEditingPost] = useState<BlogPost | null>(null);
  const [deletePost, setDeletePost] = useState<BlogPost | null>(null);
  const [form, setForm] = useState<PostForm>(emptyForm);
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState<"all" | "published" | "draft">("all");

  const [showGen, setShowGen] = useState(false);
  const [genTopic, setGenTopic] = useState("");
  const [genTone, setGenTone] = useState<"professional" | "friendly" | "persuasive">("friendly");
  const [genLang, setGenLang] = useState<"es" | "en" | "pt" | "fr" | "de" | "it">("es");
  const [uploadingCover, setUploadingCover] = useState(false);

  async function handleCoverUpload(file: File) {
    setUploadingCover(true);
    try {
      const fd = new FormData();
      fd.append("file", file);
      const res = await fetch("/api/upload", { method: "POST", body: fd });
      if (!res.ok) throw new Error("upload failed");
      const json = await res.json();
      setForm((f) => ({ ...f, coverImageUrl: json.url as string }));
      toast.success("Imagen subida");
    } catch {
      toast.error("No se pudo subir la imagen");
    } finally {
      setUploadingCover(false);
    }
  }

  const { data: posts, isLoading } = trpc.blog.adminList.useQuery();

  const backToList = () => { setView("list"); setEditingPost(null); setForm(emptyForm); };

  const createMutation = trpc.blog.create.useMutation({
    onSuccess: () => {
      toast.success("Post created");
      utils.blog.adminList.invalidate(); utils.blog.list.invalidate();
      backToList();
    },
    onError: (e) => toast.error(e.message),
  });

  const updateMutation = trpc.blog.update.useMutation({
    onSuccess: () => {
      toast.success("Post updated");
      utils.blog.adminList.invalidate(); utils.blog.list.invalidate();
      backToList();
    },
    onError: (e) => toast.error(e.message),
  });

  const publishMutation = trpc.blog.publish.useMutation({
    onSuccess: () => {
      toast.success("Post published");
      utils.blog.adminList.invalidate(); utils.blog.list.invalidate();
    },
    onError: (e) => toast.error(e.message),
  });

  const deleteMutation = trpc.blog.delete.useMutation({
    onSuccess: () => {
      toast.success("Post deleted");
      utils.blog.adminList.invalidate(); utils.blog.list.invalidate();
      setDeletePost(null);
    },
    onError: (e) => toast.error(e.message),
  });

  const generateMutation = trpc.blog.generate.useMutation({
    onSuccess: (data) => {
      setForm({
        title: data.title, slug: data.slug, excerpt: data.excerpt,
        content: data.content, category: data.category, tags: data.tags,
        author: "Lynx AI Team", readingTimeMinutes: data.readingTimeMinutes,
        status: "draft",
        coverImageUrl: "",
      });
      setShowGen(false);
      setGenTopic("");
      setEditingPost(null);
      setView("editor");
      toast.success("Draft generated — review it and publish when ready");
    },
    onError: (e) => toast.error(e.message),
  });

  if (user && user.role !== "admin") {
    navigate("/dashboard");
    return null;
  }

  function openCreate() {
    setEditingPost(null);
    setForm(emptyForm);
    setView("editor");
  }

  function openEdit(post: BlogPost) {
    setEditingPost(post);
    // Defensive tags parsing: the column may come back as a JSON string, an
    // already-parsed array, a plain comma string, or null — never let a bad
    // value throw and break the whole edit action.
    let tagsStr = "";
    try {
      const raw = post.tags as unknown;
      if (Array.isArray(raw)) {
        tagsStr = (raw as string[]).join(", ");
      } else if (typeof raw === "string" && raw.trim()) {
        const trimmed = raw.trim();
        if (trimmed.startsWith("[")) {
          const parsed = JSON.parse(trimmed);
          tagsStr = Array.isArray(parsed) ? parsed.join(", ") : trimmed;
        } else {
          tagsStr = trimmed; // already a plain comma-separated string
        }
      }
    } catch {
      tagsStr = typeof post.tags === "string" ? post.tags : "";
    }
    setForm({
      title: post.title, slug: post.slug, excerpt: post.excerpt ?? "",
      content: post.content, category: post.category ?? "",
      tags: tagsStr,
      author: post.author ?? "Lynx AI Team",
      readingTimeMinutes: post.readingTimeMinutes ?? 5, status: post.status,
      coverImageUrl: (post as { coverImageUrl?: string | null }).coverImageUrl ?? "",
    });
    setView("editor");
  }

  function handleTitleChange(title: string) {
    setForm((f) => ({ ...f, title, slug: editingPost ? f.slug : slugify(title) }));
  }

  function handleSubmit(publishNow?: boolean) {
    if (!form.title.trim() || !form.content.trim()) {
      toast.error("Title and content are required");
      return;
    }
    const tags = form.tags.split(",").map((t) => t.trim()).filter(Boolean);
    const status = publishNow ? "published" : form.status;
    const payload = {
      title: form.title, slug: form.slug || slugify(form.title),
      excerpt: form.excerpt || undefined, content: form.content,
      category: form.category || undefined, tags,
      author: form.author || undefined, readingTimeMinutes: form.readingTimeMinutes,
      status: status as "draft" | "published",
      coverImageUrl: form.coverImageUrl || undefined,
    };
    if (editingPost) updateMutation.mutate({ id: editingPost.id, ...payload });
    else createMutation.mutate(payload);
  }

  const isSaving = createMutation.isPending || updateMutation.isPending;

  const filteredPosts = (posts ?? []).filter((p) => {
    if (statusFilter !== "all" && p.status !== statusFilter) return false;
    if (search && !p.title.toLowerCase().includes(search.toLowerCase())) return false;
    return true;
  });

  // ─── EDITOR VIEW ───────────────────────────────────────────────────────────
  if (view === "editor") {
    return (
      <DashboardShell>
        <div className="p-6 max-w-6xl mx-auto">
          <div className="flex items-center justify-between mb-6 flex-wrap gap-3">
            <button onClick={backToList} className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors">
              <ArrowLeft className="w-4 h-4" /> Volver a la lista
            </button>
            <div className="flex items-center gap-2">
              <Button variant="outline" onClick={() => handleSubmit(false)} disabled={isSaving}>
                {isSaving ? "Saving..." : "Save draft"}
              </Button>
              <Button onClick={() => handleSubmit(true)} disabled={isSaving} className="lynx-gradient text-white border-0 gap-1.5">
                <Globe className="w-4 h-4" /> Publicar
              </Button>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2 space-y-4">
              <Input
                placeholder="Post title"
                value={form.title}
                onChange={(e) => handleTitleChange(e.target.value)}
                className="text-lg font-semibold h-12"
              />
              <RichTextEditor
                value={form.content}
                onChange={(html) => setForm((f) => ({ ...f, content: html }))}
                placeholder="Write your post here… Use the toolbar above to format it."
              />
            </div>

            <div className="space-y-4">
              <div className="rounded-xl border border-border/50 bg-card p-4 space-y-4">
                <div>
                  <Label className="text-xs">Extracto (resumen SEO)</Label>
                  <Textarea
                    placeholder="1-2 sentences summarizing the post"
                    value={form.excerpt}
                    onChange={(e) => setForm((f) => ({ ...f, excerpt: e.target.value }))}
                    className="mt-1 resize-none text-sm" rows={3} maxLength={500}
                  />
                </div>
                <div>
                  <Label className="text-xs">Imagen de portada</Label>
                  <div className="mt-1 flex items-center gap-3">
                    {form.coverImageUrl ? (
                      <img
                        src={form.coverImageUrl}
                        alt="Portada"
                        className="w-28 h-20 object-cover rounded-xl border border-border/40"
                        onError={(e) => { (e.currentTarget as HTMLImageElement).style.display = "none"; }}
                      />
                    ) : (
                      <div className="w-28 h-20 rounded-xl border border-dashed border-border/50 bg-muted/30 flex items-center justify-center text-muted-foreground">
                        <ImageIcon className="w-5 h-5" />
                      </div>
                    )}
                    <div className="flex flex-col gap-1.5">
                      <label>
                        <input
                          type="file"
                          accept="image/png,image/jpeg,image/webp,image/gif"
                          className="hidden"
                          onChange={(e) => {
                            const f = e.target.files?.[0];
                            if (f) handleCoverUpload(f);
                            e.currentTarget.value = "";
                          }}
                        />
                        <div className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-border/40 bg-muted/30 text-xs font-medium cursor-pointer transition-colors hover:bg-muted/60 ${uploadingCover ? "opacity-50 pointer-events-none" : ""}`}>
                          {uploadingCover ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Upload className="w-3.5 h-3.5" />}
                          {form.coverImageUrl ? "Cambiar imagen" : "Subir imagen"}
                        </div>
                      </label>
                      {form.coverImageUrl && (
                        <button
                          onClick={() => setForm((f) => ({ ...f, coverImageUrl: "" }))}
                          className="text-xs text-muted-foreground hover:text-destructive transition-colors text-left"
                        >
                          Quitar
                        </button>
                      )}
                    </div>
                  </div>
                </div>
                <div>
                  <Label className="text-xs">Slug (URL)</Label>
                  <Input
                    placeholder="url-del-articulo" value={form.slug}
                    onChange={(e) => setForm((f) => ({ ...f, slug: e.target.value }))}
                    className="mt-1 font-mono text-xs"
                  />
                  <p className="text-[11px] text-muted-foreground mt-1 truncate">/blog/{form.slug || "..."}</p>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div>
                    <Label className="text-xs">Category</Label>
                    <Input placeholder="ej: Ventas" value={form.category}
                      onChange={(e) => setForm((f) => ({ ...f, category: e.target.value }))}
                      className="mt-1 text-sm" />
                  </div>
                  <div>
                    <Label className="text-xs">Lectura (min)</Label>
                    <Input type="number" min={1} max={60} value={form.readingTimeMinutes}
                      onChange={(e) => setForm((f) => ({ ...f, readingTimeMinutes: Number(e.target.value) }))}
                      className="mt-1 text-sm" />
                  </div>
                </div>
                <div>
                  <Label className="text-xs">Autor</Label>
                  <Input value={form.author}
                    onChange={(e) => setForm((f) => ({ ...f, author: e.target.value }))}
                    className="mt-1 text-sm" />
                </div>
                <div>
                  <Label className="text-xs">Tags (separados por coma)</Label>
                  <Input placeholder="ia, ventas, chatbot" value={form.tags}
                    onChange={(e) => setForm((f) => ({ ...f, tags: e.target.value }))}
                    className="mt-1 text-sm" />
                </div>
              </div>

              <p className="text-xs text-muted-foreground px-1">
                Save as a draft to keep editing, or publish it to the public blog.
              </p>
            </div>
          </div>
        </div>
      </DashboardShell>
    );
  }

  // ─── LIST VIEW ─────────────────────────────────────────────────────────────
  const stats = {
    total: posts?.length ?? 0,
    published: posts?.filter((p) => p.status === "published").length ?? 0,
    drafts: posts?.filter((p) => p.status === "draft").length ?? 0,
  };

  return (
    <DashboardShell>
      <div className="p-6 max-w-6xl mx-auto">
        <div className="flex items-center justify-between mb-6 flex-wrap gap-3">
          <div>
            <h1 className="text-2xl font-bold flex items-center gap-2">
              <BookOpen className="w-6 h-6 text-primary" /> Blog
            </h1>
            <p className="text-sm text-muted-foreground mt-1">Manage the Lynx AI blog posts</p>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" asChild>
              <a href="/blog" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2">
                <ExternalLink className="w-4 h-4" /> Ver blog
              </a>
            </Button>
            <Button variant="outline" onClick={() => setShowGen(true)} className="gap-1.5">
              <Sparkles className="w-4 h-4 text-primary" /> Generar con IA
            </Button>
            <Button onClick={openCreate} className="lynx-gradient text-white border-0 gap-1.5">
              <Plus className="w-4 h-4" /> Nuevo
            </Button>
          </div>
        </div>

        <div className="flex items-center gap-3 mb-5 flex-wrap">
          {[
            { label: "Total", value: stats.total, key: "all" as const, icon: FileText },
            { label: "Publicados", value: stats.published, key: "published" as const, icon: Globe },
            { label: "Borradores", value: stats.drafts, key: "draft" as const, icon: FileText },
          ].map(({ label, value, key, icon: Icon }) => (
            <button
              key={key}
              onClick={() => setStatusFilter(key)}
              className={`flex items-center gap-2 rounded-lg border px-3 py-2 transition-colors ${
                statusFilter === key ? "border-primary/50 bg-primary/5" : "border-border/50 bg-card hover:border-border"
              }`}
            >
              <Icon className={`w-4 h-4 ${statusFilter === key ? "text-primary" : "text-muted-foreground"}`} />
              <span className="text-sm font-medium">{value}</span>
              <span className="text-xs text-muted-foreground">{label}</span>
            </button>
          ))}
          <div className="relative ml-auto">
            <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
            <Input placeholder="Search posts..." value={search}
              onChange={(e) => setSearch(e.target.value)} className="pl-9 w-56 h-9 text-sm" />
          </div>
        </div>

        {isLoading ? (
          <div className="space-y-3">
            {[...Array(3)].map((_, i) => (
              <div key={i} className="rounded-xl border border-border/50 bg-card p-5 animate-pulse">
                <div className="h-5 bg-muted/50 rounded w-1/2 mb-2" />
                <div className="h-4 bg-muted/50 rounded w-3/4" />
              </div>
            ))}
          </div>
        ) : filteredPosts.length === 0 ? (
          <div className="text-center py-16 rounded-xl border border-border/50 bg-card">
            <BookOpen className="w-12 h-12 text-muted-foreground/30 mx-auto mb-3" />
            <h3 className="font-semibold mb-1">
              {posts && posts.length > 0 ? "No results" : "No posts yet"}
            </h3>
            <p className="text-sm text-muted-foreground mb-4">
              {posts && posts.length > 0 ? "Try another filter or search." : "Create your first post, or let the AI draft it for you."}
            </p>
            {(!posts || posts.length === 0) && (
              <div className="flex items-center justify-center gap-2">
                <Button onClick={() => setShowGen(true)} variant="outline" className="gap-1.5">
                  <Sparkles className="w-4 h-4 text-primary" /> Generar con IA
                </Button>
                <Button onClick={openCreate} variant="outline" className="gap-1.5">
                  <Plus className="w-4 h-4" /> Crear manual
                </Button>
              </div>
            )}
          </div>
        ) : (
          <div className="space-y-3">
            {filteredPosts.map((post) => (
              <div key={post.id}
                className="rounded-xl border border-border/50 bg-card p-5 flex items-start gap-4 hover:border-primary/20 transition-colors group cursor-pointer"
                onClick={() => openEdit(post as BlogPost)}>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <h3 className="font-semibold text-sm truncate group-hover:text-primary transition-colors">{post.title}</h3>
                    <Badge variant={post.status === "published" ? "default" : "secondary"}
                      className={`text-xs shrink-0 ${post.status === "published" ? "bg-green-500/20 text-green-600 border-green-500/30" : ""}`}>
                      {post.status === "published" ? "Publicado" : "Borrador"}
                    </Badge>
                    {post.isAutoGenerated && (
                      <Badge variant="outline" className="text-xs shrink-0 text-primary border-primary/30">
                        <Rss className="w-3 h-3 mr-1" /> Auto
                      </Badge>
                    )}
                  </div>
                  <p className="text-xs text-muted-foreground line-clamp-1 mb-2">
                    {post.excerpt ?? post.content.replace(/<[^>]+>/g, "").slice(0, 120)}
                  </p>
                  <div className="flex items-center gap-4 text-xs text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <Calendar className="w-3 h-3" />
                      {post.status === "published" ? formatDate(post.publishedAt) : formatDate(post.createdAt)}
                    </span>
                    <span className="flex items-center gap-1">
                      <Clock className="w-3 h-3" /> {post.readingTimeMinutes ?? 5} min
                    </span>
                    {post.category && <span className="text-primary">{post.category}</span>}
                  </div>
                </div>

                <div className="flex items-center gap-1 shrink-0" onClick={(e) => e.stopPropagation()}>
                  {post.status === "published" && (
                    <Button size="sm" variant="ghost" className="h-8 w-8 p-0" asChild>
                      <a href={`/blog/${post.slug}`} target="_blank" rel="noopener noreferrer" title="Ver publicado">
                        <Eye className="w-4 h-4" />
                      </a>
                    </Button>
                  )}
                  {post.status === "draft" && (
                    <Button size="sm" variant="outline" className="h-8 text-xs"
                      onClick={() => publishMutation.mutate({ id: post.id })}
                      disabled={publishMutation.isPending}>
                      <Globe className="w-3 h-3 mr-1" /> Publicar
                    </Button>
                  )}
                  <Button size="sm" variant="ghost" className="h-8 w-8 p-0" title="Editar"
                    onClick={() => openEdit(post as BlogPost)}>
                    <Edit className="w-4 h-4" />
                  </Button>
                  <Button size="sm" variant="ghost" className="h-8 w-8 p-0 text-destructive hover:text-destructive" title="Eliminar"
                    onClick={() => setDeletePost(post as BlogPost)}>
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {showGen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50" onClick={() => setShowGen(false)}>
          <div className="bg-background border border-border/60 rounded-xl shadow-xl w-full max-w-md" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between px-4 py-3 border-b border-border/40">
              <p className="font-semibold flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-primary" /> Generate post with AI
              </p>
              <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => setShowGen(false)}>
                <X className="w-4 h-4" />
              </Button>
            </div>
            <div className="p-4 space-y-4">
              <div>
                <Label className="text-xs">What topic?</Label>
                <Input
                  autoFocus placeholder="e.g. How a chatbot boosts holiday sales"
                  value={genTopic} onChange={(e) => setGenTopic(e.target.value)}
                  className="mt-1" onKeyDown={(e) => { if (e.key === "Enter" && genTopic.trim()) generateMutation.mutate({ topic: genTopic, tone: genTone, language: genLang }); }}
                />
              </div>
              <div>
                <Label className="text-xs">Tono</Label>
                <div className="grid grid-cols-3 gap-2 mt-1">
                  {([
                    { key: "friendly" as const, label: "Amigable" },
                    { key: "professional" as const, label: "Profesional" },
                    { key: "persuasive" as const, label: "Vendedor" },
                  ]).map((t) => (
                    <button key={t.key} onClick={() => setGenTone(t.key)}
                      className={`text-xs py-2 rounded-lg border transition-colors ${
                        genTone === t.key ? "border-primary/50 bg-primary/10 text-primary" : "border-border/50 text-muted-foreground hover:border-border"
                      }`}>
                      {t.label}
                    </button>
                  ))}
                </div>
              </div>
              <div>
                <Label className="text-xs">Idioma</Label>
                <div className="grid grid-cols-3 gap-2 mt-1">
                  {([
                    { key: "es" as const, label: "Spanish" },
                    { key: "en" as const, label: "English" },
                    { key: "pt" as const, label: "Português" },
                    { key: "fr" as const, label: "Français" },
                    { key: "de" as const, label: "Deutsch" },
                    { key: "it" as const, label: "Italiano" },
                  ]).map((l) => (
                    <button key={l.key} onClick={() => setGenLang(l.key)}
                      className={`text-xs py-2 rounded-lg border transition-colors ${
                        genLang === l.key ? "border-primary/50 bg-primary/10 text-primary" : "border-border/50 text-muted-foreground hover:border-border"
                      }`}>
                      {l.label}
                    </button>
                  ))}
                </div>
              </div>
              <Button
                className="w-full lynx-gradient text-white border-0 gap-1.5"
                disabled={!genTopic.trim() || generateMutation.isPending}
                onClick={() => generateMutation.mutate({ topic: genTopic, tone: genTone, language: genLang })}>
                {generateMutation.isPending ? (
                  <>Generating post…</>
                ) : (
                  <><Sparkles className="w-4 h-4" /> Generar</>
                )}
              </Button>
              <p className="text-[11px] text-muted-foreground text-center">
                The AI writes a full draft. You can review and edit it before publishing.
              </p>
            </div>
          </div>
        </div>
      )}

      <AlertDialog open={!!deletePost} onOpenChange={(v) => { if (!v) setDeletePost(null); }}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete this post?</AlertDialogTitle>
            <AlertDialogDescription>
              This cannot be undone. The post "{deletePost?.title}" will be permanently deleted.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancelar</AlertDialogCancel>
            <AlertDialogAction className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              onClick={() => deletePost && deleteMutation.mutate({ id: deletePost.id })}>
              Eliminar
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </DashboardShell>
  );
}
